### ISSUE TITLE
Migrate to Hugo

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-website#1]
To aid in further significant development, and ease community contribution, including translations, it is proposed that we transition this now hard-coded site to [Hugo](https://gohugo.io/) ~~([Syna](https://themes.gohugo.io/syna/) theme).~~

This should be done, given it's breadth, via a dedicated branch. Upon completion we then transition over and remove all hard coding to return again to leaveraging the advantages of a Static Site Generator. Prior now defunct/orphaned generator was thought to be [hyde](https://github.com/hyde/hyde).

Please update the Readme.md file while tending to this issue.

Ongoing progress/TODO list:

- [x] layouts/_default/single.html fails to make title wider (span12) than content (span8)- edit now center all page titles.
- [x] make feature summary icons link to specific feature on features browse page.
- [x] add links on downloads page to sha256 checksum files for all 8 non legacy downloads.
- [x] add Partners section - likely a partial displaying yet-another hugo [section](https://gohugo.io/content-management/sections/).
- [x] Banner pic, likely Pi4 and large dash montage/collage type thing. Likely we will drop carousel. 
- [x] migrate the problems/solutions content and formatting from old site.
- [x] Constrain feature list to the same width/container as the rest of the site.
- [x] add Alerts section - likely a partial and/or block. Used to flag server maintenance etc.
- [x] DIY installer section on downloads - possibly by way of a partial.
- [x] Possibly a testing rpm (versioned) zypper repo add section on downloads (for vanilla Leap installs).
- [x] Downloads page non constrained width wise.
- [x] Fix partner logos overlapping on narrow screen.
- [x] Add missing problem/solution section to custom solutions page. Important as that is a key area for us; given we are a DIY NAS setup.

**Comment by phillxnet** [comment]
I have begun working on this issue but it is in the very early stages, nothing yet worth committing. If you have familiarity with Hugo the feel free to jump in and state you intention to do so here. Otherwise I'll stagger on with my own efforts in this direction as time allows.

We should also keep in mind that maintaining our existing public url link structure is particularly important. We have already lost our prior blog so it would be good if we could maintain existing link function for the rest of our site.

**Comment by phillxnet** [comment]
It appears from several of the most recent open issues within the Syna theme that it has suffered from a little bit-rot:
https://github.com/okkur/syna/issues
I.e. multiple references to a requirement to downgrade Hugo to 0.76.5.

- Hugo 0.76.5 released in Oct 20: https://github.com/gohugoio/hugo/releases/tag/v0.76.5
- Current Hugo version  v0.85.0 (July 21)
- There are around 17 Hugo releases between these versions.

As we are green-field here I'm keen to not start from a disadvantaged/compromised position with regard to our dependencies, i.e. the theme choice holding back the Hugo version. Now assessing other themes to consider. This is not encouraging and a concern going forward re Hugo and theme choice. Suggestions on appropriate Hugo themes are welcome.

**Comment by FroggyFlox** [comment]
> As we are green-field here I'm keen to not start from a disadvantaged/compromised position with regard to our dependencies, i.e. the theme choice holding back the Hugo version.

I completely agree with you here. Having to browse for a new theme is a setback, but it's a better choice than having to start with a compromised solution.

**Comment by phillxnet** [comment]
@FroggyFlox Yes, quite the disappointment as Syna already had many widget fits to our current arrangement. Likely not surprising as it was orientated towards open source projects. Oh well. Searching again now.

**Comment by phillxnet** [comment]
A potential theme could be: https://themes.gohugo.io/themes/hugo-hero-theme/

Simple so doesn't drag in more fragilities (read dependencies) than need be. But I'm not sure we have the images to load it up. We are also more text than images. But it does appear to be compatible with a more modern Hugo. We will also likely have to change some of the menu items names (display at least). Not sure quite what complexities this may invite.

Just noting here as there appear to be very few viable (i.e. new enough) Hugo themes to choose from.

**Comment by phillxnet** [comment]
Since a key part of transitioning to Hugo is to take advantage of the multilingual capability, the following is a multilingual filtered theme list:
https://themes.gohugo.io/tags/multilingual/

**Comment by phillxnet** [comment]
Available themes with multilingual capabilities pre-baked offer insufficient choice. However it looks like we can fairly easily extend a theme to have multilingual capabilities within it's parameters (i.e. links) and navigation (i.e. menu items) thus:

https://gohugo.io/content-management/multilingual/

and for content, linked to from the above gohugo page:

https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/

This looks, at first glance, something we can take on within our own customizations of whatever theme. Especially since one of our preferred first languages to present in is European Portuguese which is not found in many (if any) pre-baked hugo themes anyway. Hence we will have to add theme side translation anyway.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
I'll squash this branch now so it's a single commit to avoid polluting the git history with my work in progress and save points.
Pull request to follow shortly there after.
