### ISSUE TITLE
Normalise on "email" replacing "e-mail"

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-website#3]
A trivial change that should bring the website 'front' content in line with this same normalisation carried out in our Web-UI & documentation by @jonpwilson

Web-UI
pr: Replace 'e-mail' with 'email'. https://github.com/rockstor/rockstor-core/pull/2124
issue: 'Email' or 'E-mail' wording https://github.com/rockstor/rockstor-core/issues/2122

Docs:
pr:Replaced 'e-mail' with 'email' https://github.com/rockstor/rockstor-doc/pull/232
issue: "normalise on email, replacing e-mail" https://github.com/rockstor/rockstor-doc/issues/230

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by jonpwilson** [comment]
Hi Phillip,

Oh wow, I apologise for forgetting about this - to be honest I thought I'd already done it. Happy to pick this up if you've got other things to work on.

**Comment by phillxnet** [comment]
@jonpwilson Hello there.

No worries. It ended up only being 2 instances anyway. So the vast majority of this change was already done by yourself in the docs and within the Web-UI anyway. And I was doing a stint on the Web-UI so thought I'd sort it while I was in the area.

Thanks again for kicking this all off. It's nice to have standardised across the board now.

**Comment by phillxnet** [comment]
@jonpwilson Also: this website repo has only been public for a couple of weeks now so that's kind of relevant :).

Just getting it roughly in shape ready to move to Hugo.
