### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by BloodyIron** [rockstor/rockstor-website#90]
There is an egregious lack of screenshots on the website! Like, show us what your momma gave ya kind of thing. Seriously, why isn't there a screenshot section on the website? Easy content, easy traffic, easy life.

How about yes to screenshots please? :3

**Comment by phillxnet** [comment]
@BloodyIron Hello there.

You know that we have docs right? Check-out the Documentation link on the website.
Resources -> Documentation.

Linked from the product of this repository, the 'Website', but exists in it's own repository: https://github.com/rockstor/rockstor-doc

Full of screenshots  !!!

**Comment by BloodyIron** [comment]
That's not even close to what I was talking about at all... wtf
